#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*)
        if command -v cygpath > /dev/null 2>&1; then
            basedir=`cygpath -w "$basedir"`
        fi
    ;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/home/ubuntu/.local/share/pnpm/global/5/.pnpm/netlify-cli@23.13.0_@types+node@25.0.3_@vercel+blob@1.0.2_picomatch@4.0.3/node_modules/netlify-cli/bin/node_modules:/home/ubuntu/.local/share/pnpm/global/5/.pnpm/netlify-cli@23.13.0_@types+node@25.0.3_@vercel+blob@1.0.2_picomatch@4.0.3/node_modules/netlify-cli/node_modules:/home/ubuntu/.local/share/pnpm/global/5/.pnpm/netlify-cli@23.13.0_@types+node@25.0.3_@vercel+blob@1.0.2_picomatch@4.0.3/node_modules:/home/ubuntu/.local/share/pnpm/global/5/.pnpm/node_modules"
else
  export NODE_PATH="/home/ubuntu/.local/share/pnpm/global/5/.pnpm/netlify-cli@23.13.0_@types+node@25.0.3_@vercel+blob@1.0.2_picomatch@4.0.3/node_modules/netlify-cli/bin/node_modules:/home/ubuntu/.local/share/pnpm/global/5/.pnpm/netlify-cli@23.13.0_@types+node@25.0.3_@vercel+blob@1.0.2_picomatch@4.0.3/node_modules/netlify-cli/node_modules:/home/ubuntu/.local/share/pnpm/global/5/.pnpm/netlify-cli@23.13.0_@types+node@25.0.3_@vercel+blob@1.0.2_picomatch@4.0.3/node_modules:/home/ubuntu/.local/share/pnpm/global/5/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/global/5/.pnpm/netlify-cli@23.13.0_@types+node@25.0.3_@vercel+blob@1.0.2_picomatch@4.0.3/node_modules/netlify-cli/bin/run.js" "$@"
else
  exec node  "$basedir/global/5/.pnpm/netlify-cli@23.13.0_@types+node@25.0.3_@vercel+blob@1.0.2_picomatch@4.0.3/node_modules/netlify-cli/bin/run.js" "$@"
fi
